# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebd03efbeddaf5c53e4a0ea98fb8e8f0be1cb91ecce4ed06fbba06ded2391dd3c921e084908dfd0a965fca934905603e0b35455bf58854829dc9988fa484ab3b

test:
  secret_key_base: 2b590c40bbfb94924cafc61a1282484ab1df35e8b7be38d009dbb8639dc4e929d4a0f6c78b9273e15f8f3984f9f00d83c0d1f1fc44d99305beb416ac4061d697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
